/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "cla.v:3.1-21.10" *)
module cla(A, B, Cin, Sum, Cout);
  (* src = "cla.v:5.17-5.18" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "cla.v:5.19-5.20" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "cla.v:6.8-6.11" *)
  input Cin;
  wire Cin;
  (* src = "cla.v:8.9-8.13" *)
  output Cout;
  wire Cout;
  (* src = "cla.v:7.18-7.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "cla.v:10.6-10.11" *)
  wire \carry[0] ;
  (* src = "cla.v:10.6-10.11" *)
  wire \carry[1] ;
  (* src = "cla.v:10.6-10.11" *)
  wire \carry[2] ;
  (* src = "cla.v:10.6-10.11" *)
  wire \carry[3] ;
  (* src = "cla.v:10.6-10.11" *)
  wire \carry[4] ;
  (* module_not_derived = 32'd1 *)
  (* src = "cla.v:18.8-18.73" *)
  test \genblk1[0].T  (
    .A(A[0]),
    .B(B[0]),
    .C(\carry[1] ),
    .Cin(Cin),
    .S(Sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla.v:18.8-18.73" *)
  test \genblk1[1].T  (
    .A(A[1]),
    .B(B[1]),
    .C(\carry[2] ),
    .Cin(\carry[1] ),
    .S(Sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla.v:18.8-18.73" *)
  test \genblk1[2].T  (
    .A(A[2]),
    .B(B[2]),
    .C(\carry[3] ),
    .Cin(\carry[2] ),
    .S(Sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla.v:18.8-18.73" *)
  test \genblk1[3].T  (
    .A(A[3]),
    .B(B[3]),
    .C(Cout),
    .Cin(\carry[3] ),
    .S(Sum[3])
  );
  assign \carry[0]  = Cin;
  assign \carry[4]  = Cout;
endmodule

(* src = "test.v:3.1-14.10" *)
module test(A, B, Cin, S, C);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "test.v:4.7-4.8" *)
  input A;
  wire A;
  (* src = "test.v:4.9-4.10" *)
  input B;
  wire B;
  (* src = "test.v:5.11-5.12" *)
  output C;
  wire C;
  (* src = "test.v:4.11-4.14" *)
  input Cin;
  wire Cin;
  (* src = "test.v:5.8-5.9" *)
  output S;
  wire S;
  gf180mcu_fd_sc_mcu9t5v0__clkinv_1 _3_ (
    .I(Cin),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _4_ (
    .A1(A),
    .A2(B),
    .ZN(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nor2_1 _5_ (
    .A1(A),
    .A2(B),
    .ZN(_2_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor3_1 _6_ (
    .A1(A),
    .A2(B),
    .A3(Cin),
    .Z(S)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _7_ (
    .A1(_0_),
    .A2(_2_),
    .B(_1_),
    .ZN(C)
  );
endmodule
